### ISSUE TITLE
Add support for CMake installation

### ISSUE THREAD

**Issue by koral--** [bitrise-steplib/steps-install-missing-android-tools#41]
Since AGP 3.0 you can specify required CMake version: https://developer.android.com/studio/projects/add-native-code#vanilla_cmake
It can come either from Android SDK component or just be available in PATH.

Currently step fails with `Failed to ensure android components, error: output: FAILURE: Build failed with an exception.` when it encounters not installed version of CMake.

Build URL: https://app.bitrise.io/build/aaeee66c910de477

**Comment by godrei** [comment]
Hi @koral-- ,
thanks for the report, task scheduled to fix this.

**Comment by lszucs** [comment]
Hi @koral-- ,

We have rolled out a new version of the step since your report, which should resolve this issue -- apparently, I wasn't able to reproduce it with the recent version.

Also, I was unable to open your build. 

Can you confirm if this is an outstanding issue for you?

**Comment by koral--** [comment]
Nub of the problem is still reproducible. 
The only change is that now step does not fail. However, it also does not install requested version of cmake.
To fix this issue you need to add the following logic to step:

1. obtain cmake version from configuration
2. if it is not available install it using sdkamanger

In the more sophisticated version: if requested version is not available in sdkamanager, try to install it using apt-get or brew.

Note that you should also take `cmake.dir` property into account.

**Comment by lszucs** [comment]
Hi @koral-- ,

There are two things we're talking about here. Android gradle plugin can and will automatically install `cmake` versions supported by `sdkmanager` (`cmake;3.10.2.4988404`, `cmake;3.6.4111459`), if the appropriate licenses are accepted. I was able to reproduce a failing gradle build only when caused by license issues (or general gradle misconfiguration). These license related issues were resolved recently.

Installing a custom `cmake` version is another thing, and is indeed a missing feature. 

Now, back to the `sdkmanager` versions. I can't access your build, maybe the support user isn't enabled. However, I would possibly have to see your gradle configuration to tell what might be wrong, because if I run the step against a built-in Android Studio NDK sample project with our Android NDK docker images, `cmake` is installed by `sdkmanager` correctly -- however, if I just add the aforementioned `cmake {...}` closure you referenced from the docs, to an ordinary Android project, nothing happens, as if the android gradle plugin would be smart enough to determine if the project truly depends on `cmake`.

If you enable the support user, our current engineer on support can take a look into what might be wrong in your build.

So what is your main point with this issue? Do you want to use a built-in `cmake` version and get it installed? Or is this intended as a feature request for  supporting any version of `cmake`?

**Comment by koral--** [comment]
Sorry, for missing support user, I've just enabled access.
And here is the build.gradle: https://gist.github.com/koral--/254d4cdca91ce88a2877a1d6b38d645b

> Android gradle plugin can and will automatically install

AGP (since version approx 2.2.0) will try to install all the missing SDK components. Moreover AFAIK custom cmake version has been added in later version. So in practice all the users which have cmake version specified will also have it installed during build. However, it seems that it won't happen during this step but when executing some of the next ones (probably invoking `assemble` or similar task).

If it is intended/acceptable that this step won't actually install some of the missing components but it will ensure that all the licenses are accepted so those components will be installed anyway in later steps then there is no issue here. 

However, if purpose of this step is to actually install everything needed and fail if installation fails (e.g. Google has suddenly changed some licenses) then some part of the functionality is missing.

> So what is your main point with this issue? Do you want to use a built-in `cmake` version and get it installed? Or is this intended as a feature request for supporting any version of `cmake`?

I don't have any particular problem in my project. It is a pure feature request.

**Comment by lszucs** [comment]
Hi @koral--,

I looked at your gradle file. Indeed, if you just insert the `cmake` closure into a simple Android project, gradle will not install `cmake`. Your actual build has to depend on it, like the built-in C/C++ enabled examples from Android Studio.

Unfortunately, I can't tell which exact configuration item is required for AGP to recognize the project as dependent on `cmake`, but the gradle file you posted is definitely not sufficient.

If you are interested in getting to the bottom of this and need any assistance, I recommend contacting support and the (L3) support engineer will probably be able to help out.

Otherwise, since you don't have a build issue, I'd create a feature request of the general cmake installation functionality on Discourse and close this GitHub issue, if you are fine with that.

**Comment by koral--** [comment]
OK, I agree.
Here is the Feature Request: https://discuss.bitrise.io/t/add-support-for-cmake-version-not-available-via-sdkmanager/8053
