### ISSUE TITLE
Failed to download NDK bundle, error: could not locate platform dir at ndk home: /opt/android-ndk

### ISSUE THREAD

**Issue by TheSpartan94** [bitrise-steplib/steps-install-missing-android-tools#74]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.3.x
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- This issue may happen with NDK (> 19) according to NDK documentation

### Issue description

_Failed to download NDK bundle, error: could not locate platform dir at ndk home: /opt/android-ndk_

This happens because the "platform" dir has been deleted in NDK releases > 19, but the step of this repository still looks for this folder. I've been trying with the latest NDK (22) and still got this issue. I solved by using NDK 18, but still I would like to use the latest versions
### Bitrise info

- Build URL: https://app.bitrise.io/build/e05b81de0c7e4423 (may be private)
- Log: `Configs:
- GradlewPath: ./gradlew
- AndroidHome: /opt/android-sdk-linux
- NDKRevision: 22
Preparation
Set executable permission for gradlew
Installing NDK bundle
NDK home: /opt/android-ndk
Cleaning
Downloading
searching for platforms dir in /opt/android-ndk
Failed to download NDK bundle, error: could not locate platform dir at ndk home: /opt/android-ndk`

### Steps to reproduce

1. To reproduce this issue, just add a revision for the NDK like 19 or above it (Latest is 22).

**Comment by prcaen** [comment]
We also have this issue, when we switch the stack from Docker Ubuntu 16.X to 20.04

**Comment by Roland-Bak** [comment]
Hello everyone 👋

I wanted to let you know that this is a know issue, and our developers have just very recently deployed a fix for this, so the issue should be solved! 🎉 

Let me know if you experience otherwise! 🙂

**Comment by AndreasBoehm** [comment]
Hi @Roland-Bak,

i am still experiencing this issue today.
Do you have any version numbers or anything so we can compare if we are already running the version that contains the fix?

Thanks

**Comment by Roland-Bak** [comment]
Hi @AndreasBoehm 👋

Are you using the latest Ubuntu stack (20.04)?

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂

**Comment by AndreasBoehm** [comment]
> Hi @AndreasBoehm 👋
> 
> Are you using the latest Ubuntu stack (20.04)?
> 
> Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( [devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) ) so that we can take a more in-depth look? 🙂

Hi @Roland-Bak,

yes, i am using the latest Ubuntu stack 20.04.

Build URL: https://app.bitrise.io/build/2928cd2d-422f-4271-8db7-d3d971c4b863
Support Access has been enabled 👍

**Comment by Roland-Bak** [comment]
Hi @AndreasBoehm 👋

I wanted to let you know that our developers are still working on fixing this, I've been informed that this issue is currently being worked on in their current sprint, so bear with us! 🙂

**Comment by AndreasBoehm** [comment]
Thank you for the update @Roland-Bak

**Comment by ofalvai** [comment]
Hello everyone 👋 

We released [version 2.4.0](https://github.com/bitrise-steplib/steps-install-missing-android-tools/releases/tag/2.4.0) that fixes all sorts of NDK installation problems. Please upgrade this step in your workflows and let us know about the results.

**Comment by AndreasBoehm** [comment]
Thanks for the effort @ofalvai!

Unfortunately I still get the following warning that indicates that the NDK can't be found from my build.
```
Unable to strip the following libraries, packaging them as they are: libgmm-jni.so.
```
and
```
Unable to extract native debug metadata from /bitrise/src/app/build/intermediates/merged_native_libs/qa/out/lib/arm64-v8a/libgmm-jni.so because unable to locate the objcopy executable for the arm64-v8a ABI.
Unable to extract native debug metadata from /bitrise/src/app/build/intermediates/merged_native_libs/qa/out/lib/x86_64/libgmm-jni.so because unable to locate the objcopy executable for the x86_64 ABI.
Unable to extract native debug metadata from /bitrise/src/app/build/intermediates/merged_native_libs/qa/out/lib/x86/libgmm-jni.so because unable to locate the objcopy executable for the x86 ABI.
Unable to extract native debug metadata from /bitrise/src/app/build/intermediates/merged_native_libs/qa/out/lib/armeabi-v7a/libgmm-jni.so because unable to locate the objcopy executable for the armeabi-v7a ABI.
````

My **build.gradle**
```
android {
	defaultConfig {
		ndkVersion "22.0.7026061"
	}
}
```

**Comment by ofalvai** [comment]
@AndreasBoehm 

If you define a specific NDK version in your Gradle config, then we recommend installing that specific version of NDK in your workflow. This step only allows specifying the major version (for now), but at the time of writing this using `22` will install `22.0.7026061`, which is exactly what's defined in your config.

For more precise needs, we recommend calling `sdkmanager` directly (it's preinstalled on the stacks), like this: `sdkmanager --install "ndk;21.1.6273396"`

**Comment by AndreasBoehm** [comment]
> @AndreasBoehm
> 
> If you define a specific NDK version in your Gradle config, then we recommend installing that specific version of NDK in your workflow. This step only allows specifying the major version (for now), but at the time of writing this using `22` will install `22.0.7026061`, which is exactly what's defined in your config.
> 
> For more precise needs, we recommend calling `sdkmanager` directly (it's preinstalled on the stacks), like this: `sdkmanager --install "ndk;21.1.6273396"`

Thanks @ofalvai, installing the NDK using `sdkmanager` works fine 👍
